[tool.poetry]
name = "ordering-simulator"
version = "0.1.0"
description = "Text-based ordering simulator for McDonald's."
authors = ["Zakharii Tepliakov <zakhariitepliakov@gmail.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.13"
pyyaml = "^6.0.3"
pydantic = "^2.12.5"
python-dotenv = "^1.2.1"
google-genai = "^1.52.0"

[build-system]
requires = ["poetry-core>=1.6"]
build-backend = "poetry.core.masonry.api"
